version: '3.8'

services:
  web:
    build: .
    expose:
      - "81"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=production
      - SECRET_KEY=una_clave_secreta_muy_segura_123
    restart: always
    networks:
      - coolify

networks:
  coolify:
    external: true
